#[package] #do not use it will think of package and not workspace
#name = "rustmoduleworldeditor"
#version = "0.1.0"
#authors = ["Lightnet <>"]
#edition = "2018"

[workspace]
members = [
    "imguimodule",
    "amethystmoduleworld",
    "pistonmoduleworld",
    "kiss3dnmoduleworld"
]