[package]
name = "gfxmodule"
version = "0.1.0"
authors = ["Lightnet <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = "0.18"
glutin = "0.21.1"
gfx_window_glutin = "0.31.0"